---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: dev
    labels:
      - dependencies
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: daily
