# The following settings determine which data is loaded by init_pudl.py

# You can create several different settings files if you wish, and specify
# which one the initialization script uses on the command line:
#
# ./init_pudl.py -f custom_settings.yml
#
# The default settings load nothing into the database, but there are commented
# out lines enumerating the full extent of the currently loadable data, which
# you can un-comment or edit to suit your data analysis.

# There are many more data tables in the original FERC Form 1 that have not
# yet been integrated. If they are of interest to you, please let the folks at
# Catalyst Cooperative know: hello@catalyst.coop
ferc1_tables:
 - fuel_ferc1 # fuel_ferc1 requires plants_steam_ferc1 to load properly
 - plants_steam_ferc1
 - plants_small_ferc1
 - plants_hydro_ferc1
 - plants_pumped_storage_ferc1
 - plant_in_service_ferc1
 - purchased_power_ferc1
 - accumulated_depreciation_ferc1

ferc1_years: []
# ferc1_years: [2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
#              2013, 2014, 2015, 2016, 2017]

# if you are loading ferc1, you need to specify a reference year. This is the
# year whose database structure is used as a template. If unspecified
# the default will be the most recent year in ferc1_years
ferc1_ref_year: 2017

# This is the full list of EIA 923 tables.  Many of them are interdependent,
# and are used in the definition of the overall database, so it is recommended
# that you import either all of them or none of them. Additionally, there
# are many relationships between the EIA 923 and EIA 860 tables, and in general
# they should be imported together.
eia923_tables:
  - plants_eia923
  - generation_fuel_eia923
  - plant_ownership_eia923
  - boiler_fuel_eia923
  - boilers_eia923
  - generators_eia923
  - generation_eia923
  - coalmine_eia923 # coalmine_eia923 REQUIRES fuel_receipts_costs_eia923
  - fuel_receipts_costs_eia923

eia923_years: []
# eia923_years: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

# See notes above about the entanglement between EIA 923 and EIA 860. It's best
# to load all the tables from both of them, or neither of them.
eia860_tables:
  - boiler_generator_assn_eia860
  - utilities_eia860
  - plants_eia860
  - generators_eia860
  - ownership_eia860

eia860_years: []
# eia860_years: [2011, 2012, 2013, 2014, 2015, 2016, 2017]

# The EPA CEMS data goes back as far as 1995, but before 2000 it is not as
# complete.  Note that the EPA CEMS data set is much larger than any of the
# other data sets here.  Pulling in all the years of data for all of the
# states requires ~100GB of free disk space and takes around 8 hours on a
# reasonably fast laptop.
epacems_years: [2016]
#epacems_years: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
#                2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
#epacems_states: []
epacems_states: [CO]
#epacems_states: [ALL]

# If verbose is True, the script will print out a progress report as it runs
verbose: True

# These settings are mostly used for development work, testing the ETL process.
# If you set pudl_testing or ferc1_testing to true, then instead of populating
# the live pudl and ferc1 databases in postgresql, the initialization script
# will attempt to populate pudl_test and ferc1_test.  This is useful if you
# have a working database and don't want to clobber it while testing.
ferc1_testing: False
pudl_testing: False
keep_csv: False
debug: False
