---
name: Build and publish Docker image
on:
  push:
    branches:
      #- main
      #- dev
      #- 'sprint*'
      - dockerbuild # for testing purposes
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Retrieve history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.1.0
        with:
          images: catalystcoop/pudl_etl
          tag-sha: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #      - name: Set up Python 3.7
          #        uses: actions/setup-python@v1
          #        with:
          #          python-version: 3.7
          #      - name: Prep build environment
          #        run: |
          #          python -m pip install --upgrade pip
          #          pip install setuptools wheel
          #      - name: Build PyPI tarball
          #        run: python setup.py sdist
      #      - name: Determine version
      #        run: python setup.py --version
      #- name: Install build environment
      # run: python -m pip install build --user
      #      - name: Build source tarball
      # run: python -m build --sdist --outdir dist/ .
      # TODO(rousik): inject tarball into the docker image
      #      - name: Debug print requirements
      #        run: python devtools/print_requirements.py
      #      - name: Docker Meta
      #        id: docker_meta
      #        uses: crazy-max/ghaction-docker-meta@v4.1.0
      #        with:
      #          tag-sha: true
      #          images: catalystcoop/pudl_etl
      #      - name: List local environment
      #        run: ls -la
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v1
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1
      #      - name: Login to DockerHub
      #        if: github.event_name != 'pull_request'
      #        uses: docker/login-action@v2.1.0
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Build and push
      #        uses: docker/build-push-action@v3.2.0
      #        with:
      #          file: release/Dockerfile.tiny
      #          push: ${{ github.event_name != 'pull_request' }}
      #          tags: ${{ steps.docker_meta.outputs.tags }}
      #          #          cache-from: type=registry,ref=catalystcoop/pudl_etl:latest
      #          cache-to: type=inline
      # TODO(rousik): should we use caching?

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          file: release/Dockerfile.tiny
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
